from tkinter import *
import sqlite3
root=Tk()
root.title("BOKKSTORE MANAGEMENT SYSTEM")
p=PhotoImage(file='H:\\PYTHON\\image.gif')
p1=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\studies.gif')
p2=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\fiction.gif')
p3=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\cartoons.gif')
p4=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\biography.gif')
p5=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\health.gif')
p6=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\let us c.png')
p7=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\STUDIES\\s1.GIF')
p8=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\datac.png')
p9=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\STUDIES\\s2.GIF')
p10=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\corepython.png')
p11=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\STUDIES\\s3.GIF')
p12=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\maths.png')
p13=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\STUDIES\\s4.GIF')
p14=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\bee.png')
p15=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\STUDIES\\s5.GIF')
p16=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\harrypotter.png')
p17=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\FICTION\\image1.GIF')
p18=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\twilight.png')
p19=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\FICTION\\image2.GIF')
p20=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\lifeofpi.png')
p21=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\FICTION\\image3.GIF')
p22=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\divergent.png')
p23=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\FICTION\\image4.GIF')
p24=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\got.png')
p25=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\FICTION\\image5.GIF')
p26=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\steve.png')
p27=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\BIOGRAPHY\\image1.GIF')
p28=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\bill.png')
p29=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\BIOGRAPHY\\image2.GIF')
p30=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\apj.png')
p31=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\BIOGRAPHY\\image3.GIF')
p32=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\malala.png')
p33=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\BIOGRAPHY\\image4.GIF')
p34=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\karan.png')
p35=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\BIOGRAPHY\\image5.GIF')
p36=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\tintin.png')
p37=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\CARTOONS\\image1.GIF')
p38=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\snowwhite.png')
p39=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\CARTOONS\\image2.GIF')
p40=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\children.png')
p41=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\CARTOONS\\image3.GIF')
p42=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\junglebook.png')
p43=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\CARTOONS\\image4.GIF')
p44=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\gulliver.png')
p45=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\CARTOONS\\image5.GIF')
p46=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\flatdiet.png')
p47=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\HEALTH\\image1.GIF')
p48=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\eatcomplete.png')
p49=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\HEALTH\\image2.GIF')
p50=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\arthealth.png')
p51=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\HEALTH\\image3.GIF')
p52=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\metabolism.png')
p53=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\HEALTH\\image4.GIF')
p54=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\pillars.png')
p55=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\HEALTH\\image5.GIF')
p56=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\image2.png')
p57=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\image3.gif')
p58=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\image4.png')
p59=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\c1 text.png')
p60=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\c1.png')
p61=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\c2 text.png')
p62=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\c2.png')
p63=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\d1 text.png')
p64=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\d1.png')
p65=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\d2 text.png')
p66=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\d2.png')
p67=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\p1 text.png')
p68=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\p1.png')
p69=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\p2 text.png')
p70=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\p2.png')
p71=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\m1 text.png')
p72=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\m1.png')
p73=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\m2 text.png')
p74=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\m2.png')
p75=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\b1 text.png')
p76=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\b1.png')
p77=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\b2 text.png')
p78=PhotoImage(file='C:\\Users\\HP\\Desktop\\New Folder\\b2.png')
def home(self):
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p56)
    l0.place(x=200,y=75)
    l1=Label(f1,text="KITAB KHANA",bg='black',fg='white',font=('times','30','bold underline'))
    l1.place(x=600,y=10)
    b1=Button(f1,text="STUDIES",font=('Courier','25','bold'))
    b1.place(x=450,y=200)
    b1.bind("<Button-1>",studies)
    b2=Button(f1,text="FICTION",font=('Courier','25','bold'))
    b2.place(x=450,y=400)
    b2.bind("<Button-1>",fiction)
    b3=Button(f1,text="CARTOONS",font=('Courier','25','bold'))
    b3.place(x=650,y=600)
    b3.bind("<Button-1>",cartoons)
    b4=Button(f1,text="BIOGRAPHY",font=('Courier','25','bold'))
    b4.place(x=850,y=200)
    b4.bind("<Button-1>",biography)
    b5=Button(f1,text="HEALTH",font=('Courier','25','bold'))
    b5.place(x=850,y=400)
    b5.bind("<Button-1>",health)
    b6=Button(f1,text='EXIT',font=('times','15','bold'))
    b6.place(x=1450,y=10)
    b6.bind("<Button-1>",exit)
            
def login(self):
    conn=sqlite3.connect('book.db')
    with conn:
        cursor=conn.cursor()
    query='SELECT Username,Password from login'
    cursor.execute(query)
    for row in cursor:
        if((row[0]==t1.get()) and (row[1]==t2.get())):
            f1=Frame(root,bg='black',width=2000,height=2000)
            f1.place(x=0,y=0)
            l0=Label(f1,image=p56)
            l0.place(x=200,y=75)
            l1=Label(f1,text="KITAB KHANA",bg='black',fg='white',font=('times','30','bold underline'))
            l1.place(x=600,y=10)
            b1=Button(f1,text="STUDIES",font=('Courier','25','bold'))
            b1.place(x=450,y=200)
            b1.bind("<Button-1>",studies)
            b2=Button(f1,text="FICTION",font=('Courier','25','bold'))
            b2.place(x=450,y=400)
            b2.bind("<Button-1>",fiction)
            b3=Button(f1,text="CARTOONS",font=('Courier','25','bold'))
            b3.place(x=650,y=600)
            b3.bind("<Button-1>",cartoons)
            b4=Button(f1,text="BIOGRAPHY",font=('Courier','25','bold'))
            b4.place(x=850,y=200)
            b4.bind("<Button-1>",biography)
            b5=Button(f1,text="HEALTH",font=('Courier','25','bold'))
            b5.place(x=850,y=400)
            b5.bind("<Button-1>",health)
            b6=Button(f1,text='EXIT',font=('times','15','bold'))
            b6.place(x=1450,y=10)
            b6.bind("<Button-1>",exit)

def register(self):
    FirstName=StringVar()
    Lastname=StringVar()
    Email=StringVar()
    Contact=IntVar()
    Username=StringVar()
    Password=StringVar()
    def submit(self):
        fname=t1.get()
        lname=t2.get()
        email=t3.get()
        contact=t4.get()
        user=t5.get()
        password=t7.get()
        conn = sqlite3.connect('book.db')
        with conn:
          cursor = conn.cursor()
        cursor.execute('CREATE TABLE IF NOT EXISTS login (Username TEXT ,Password TEXT)')
        cursor.execute('CREATE TABLE IF NOT EXISTS register (FirstName TEXT,Lastname TEXT,Email TEXT,Contact TEXT,Username TEXT,Password TEXT)')
        cursor.execute('INSERT INTO register (FirstName,Lastname,Email,Contact,Username,Password) VALUES(?,?,?,?,?,?)',(fname,lname,email,contact,user,password))
        cursor.execute('INSERT INTO login(Username,Password) VALUES(?,?)',(user,password))
        conn.commit()
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p56)
    l0.place(x=250,y=100)
    l1=Label(f1,text="REGISTRATION FORM",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=550,y=10)
    l2=Label(f1,text="FIRST NAME",font=('times','15'))
    l2.place(x=350,y=150)
    t1=Entry(f1,width=40)
    t1.place(x=600,y=150)
    l=Label(f1,text="LAST NAME",font=('times','15'))
    l.place(x=350,y=250)
    t2 = Entry(f1, width=30)
    t2.place(x=600,y=250)
    l3=Label(f1,text="EMAIL_ID",font=('times','15'))
    l3.place(x=350,y=350)
    t3=Entry(f1,width=30)
    t3.place(x=600,y=350)
    l4=Label(f1,text="CONTACT_NO",font=('times','15'))
    l4.place(x=350,y=450)
    t4 = Entry(f1, width=30)
    t4.place(x=600,y=450)
    l5=Label(f1,text="USERNAME",font=('times','15'))
    l5.place(x=350,y=550)
    t5 = Entry(f1,width=30)
    t5.place(x=600,y=550)
    l6=Label(f1,text="PASSWORD",font=('times','15'))
    l6.place(x=350,y=650)
    t6 = Entry(f1,width=30)
    t6.place(x=600,y=650)
    t7=Entry(f1,width=30,show="*")
    t7.place(x=600,y=650)
    b1=Button(f1,text="SUBMIT",font=('Courier','30','bold'))
    b1.place(x=950,y=700)
    b1.bind("<Button-1>",submit)    



def studies(self):
    f.destroy()
    f2=Frame(root,bg='black',width=2000,height=2000)
    f2.place(x=0,y=0)
    l0=Label(f2,image=p1)
    l0.place(x=50,y=150)
    l1=Label(f2,text="STUDIES",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f2,text="C LANGUAGE",font=('Courier','25','bold'))
    b1.place(x=850,y=200)
    b1.bind("<Button-1>",clang)
    b2=Button(f2,text="DATA STRUCTURES",font=('Courier','25','bold'))
    b2.place(x=850,y=300)
    b2.bind("<Button-1>",ds)
    b3=Button(f2,text="PYTHON LANGUAGE",font=('Courier','25','bold'))
    b3.place(x=850,y=400)
    b3.bind("<Button-1>",pyth)
    b4=Button(f2,text="MATHEMATICS",font=('Courier','25','bold'))
    b4.place(x=850,y=500)
    b4.bind("<Button-1>",maths)
    b5=Button(f2,text="BASIC ELECTRICAL ENGINEERING",font=('Courier','25','bold'))
    b5.place(x=850,y=600)
    b5.bind("<Button-1>",bee)
    b6=Button(f2,text='BACK',font=('times','15','bold'))
    b6.place(x=10,y=10)
    b6.bind("<Button-1>",home)
    b7=Button(f2,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def fiction(self):
    f.destroy()
    f3=Frame(root,bg='black',width=2000,height=2000)
    f3.place(x=0,y=0)
    l0=Label(f3,image=p2)
    l0.place(x=150,y=100)
    l1=Label(f3,text="FICTION",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f3,text="HARRY POTTER",font=('Courier','25','bold'))
    b1.place(x=350,y=200)
    b1.bind("<Button-1>",harry)
    b2=Button(f3,text="TWILIGHT",font=('Courier','25','bold'))
    b2.place(x=350,y=400)
    b2.bind("<Button-1>",twilight)
    b3=Button(f3,text="LIFE OF PI",font=('Courier','25','bold'))
    b3.place(x=850,y=400)
    b3.bind("<Button-1>",lifeofpi)
    b4=Button(f3,text="DIVERGENT",font=('Courier','25','bold'))
    b4.place(x=850,y=200)
    b4.bind("<Button-1>",divergent)
    b5=Button(f3,text="GAME OF THRONES",font=('Courier','25','bold'))
    b5.place(x=550,y=600)
    b5.bind("<Button-1>",got)
    b6=Button(f3,text='BACK',font=('times','15','bold'))
    b6.place(x=10,y=10)
    b6.bind("<Button-1>",home)
    b7=Button(f3,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def cartoons(self):
    f.destroy()
    f4=Frame(root,bg='black',width=2000,height=2000)
    f4.place(x=0,y=0)
    l0=Label(f4,image=p3)
    l0.place(x=100,y=100)
    l1=Label(f4,text="CARTOONS",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f4,text="THE JUNGLE BOOK",font=('Courier','25','bold'))
    b1.place(x=250,y=200)
    b1.bind("<Button-1>",junglebook)
    b2=Button(f4,text="SNOW WHITE",font=('Courier','25','bold'))
    b2.place(x=250,y=400)
    b2.bind("<Button-1>",snowwhite)
    b3=Button(f4,text="TINTIN",font=('Courier','25','bold'))
    b3.place(x=850,y=400)
    b3.bind("<Button-1>",tintin)
    b4=Button(f4,text="GREAT STORIES FOR CHILDREN",font=('Courier','25','bold'))
    b4.place(x=500,y=600)
    b4.bind("<Button-1>",stories)
    b5=Button(f4,text="GULLIVERS TRAVELS",font=('Courier','25','bold'))
    b5.place(x=850,y=200)
    b5.bind("<Button-1>",gulliver)
    b6=Button(f4,text='BACK',font=('times','15','bold'))
    b6.place(x=10,y=10)
    b6.bind("<Button-1>",home)
    b7=Button(f4,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def biography(self):
    f.destroy()
    f5=Frame(root,bg='black',width=2000,height=2000)
    f5.place(x=0,y=0)
    l0=Label(f5,image=p4)
    l0.place(x=700,y=150)
    l1=Label(f5,text="BIOGRAPHY",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f5,text="STEVE JOBS",font=('Courier','25','bold'))
    b1.place(x=150,y=200)
    b1.bind("<Button-1>",steve)
    b2=Button(f5,text="BILL GATES",font=('Courier','25','bold'))
    b2.place(x=150,y=300)
    b2.bind("<Button-1>",bill)
    b3=Button(f5,text="APJ ABDUL KALAM",font=('Courier','25','bold'))
    b3.place(x=150,y=400)
    b3.bind("<Button-1>",apj)
    b4=Button(f5,text="MALALA",font=('Courier','25','bold'))
    b4.place(x=150,y=500)
    b4.bind("<Button-1>",malala)
    b5=Button(f5,text="KARAN JOHAR",font=('Courier','25','bold'))
    b5.place(x=150,y=600)
    b5.bind("<Button-1>",karan)
    b6=Button(f5,text='BACK',font=('times','15','bold'))
    b6.place(x=10,y=10)
    b6.bind("<Button-1>",home)
    b7=Button(f5,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def health(self):
    f.destroy()
    f6=Frame(root,bg='black',width=2000,height=2000)
    f6.place(x=0,y=0)
    l0=Label(f6,image=p5)
    l0.place(x=20,y=70)
    l1=Label(f6,text="HEALTH",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f6,text="FLAT BELLY DIET",font=('Courier','25','bold'))
    b1.place(x=250,y=200)
    b1.bind("<Button-1>",diet)
    b2=Button(f6,text="EAT COMPLETE",font=('Courier','25','bold'))
    b2.place(x=250,y=400)
    b2.bind("<Button-1>",eatcomplete)
    b3=Button(f6,text="ART OF HEALTH",font=('Courier','25','bold'))
    b3.place(x=850,y=400)
    b3.bind("<Button-1>",arthealth)
    b4=Button(f6,text="MASTER YOUR METABOLISM",font=('Courier','25','bold'))
    b4.place(x=850,y=200)
    b4.bind("<Button-1>",metabolism)
    b5=Button(f6,text="SEVEN PILLARS OF HEALTH",font=('Courier','25','bold'))
    b5.place(x=450,y=600)
    b5.bind("<Button-1>",pillars)
    b6=Button(f6,text='BACK',font=('times','15','bold'))
    b6.place(x=10,y=10)
    b6.bind("<Button-1>",home)
    b7=Button(f6,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def clang(self):
    f.destroy()
    f2=Frame(root,bg='black',width=2000,height=2000)
    f2.place(x=0,y=0)
    l0=Label(f2,image=p1)
    l0.place(x=700,y=150)
    l1=Label(f2,text="C LANGUAGE",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f2,text="BY YASHAVANT P. KATNEKAR",font=('Courier','25','bold'))
    b1.place(x=100,y=150)
    b1.bind("<Button-1>",letusc)
    b2=Button(f2,text="BY REEMA THAREJA",font=('Courier','25','bold'))
    b2.place(x=100,y=250)
    b2.bind("<Button-1>",cprog1)
    b3=Button(f2,text="BY DARREL L. GRAHAM",font=('Courier','25','bold'))
    b3.place(x=100,y=350)
    b3.bind("<Button-1>",cprog2)
    b4=Button(f2,text='BACK',font=('times','15','bold'))
    b4.place(x=10,y=10)
    b4.bind("<Button-1>",studies)
    b5=Button(f2,text='EXIT',font=('times','15','bold'))
    b5.place(x=1450,y=10)
    b5.bind("<Button-1>",exit)

def ds(self):
    f.destroy()
    f2=Frame(root,bg='black',width=2000,height=2000)
    f2.place(x=0,y=0)
    l0=Label(f2,image=p1)
    l0.place(x=700,y=150)
    l1=Label(f2,text="DATA STRUCTURES",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f2,text="BY REEMA THAREJA",font=('Courier','25','bold'))
    b1.place(x=100,y=150)
    b1.bind("<Button-1>",reemads)
    b2=Button(f2,text="BY SEYMOUR LIPSHUTZ",font=('Courier','25','bold'))
    b2.place(x=100,y=250)
    b2.bind("<Button-1>",seymour)
    b3=Button(f2,text="BY BALAGURUSAMY",font=('Courier','25','bold'))
    b3.place(x=100,y=350)
    b3.bind("<Button-1>",bala)
    b4=Button(f2,text='BACK',font=('times','15','bold'))
    b4.place(x=10,y=10)
    b4.bind("<Button-1>",studies)
    b5=Button(f2,text='EXIT',font=('times','15','bold'))
    b5.place(x=1450,y=10)
    b5.bind("<Button-1>",exit)

def pyth(self):
    f.destroy()
    f2=Frame(root,bg='black',width=2000,height=2000)
    f2.place(x=0,y=0)
    l0=Label(f2,image=p1)
    l0.place(x=700,y=150)
    l1=Label(f2,text="PYTHON LANGUAGE",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f2,text="BY R. NAGESHWARA RAO",font=('Courier','25','bold'))
    b1.place(x=100,y=150)
    b1.bind("<Button-1>",corepy)
    b2=Button(f2,text="BY TIMOTHY C. NEEDHAM",font=('Courier','25','bold'))
    b2.place(x=100,y=250)
    b2.bind("<Button-1>",py1)
    b3=Button(f2,text="BY RAMSEY HAMILTON",font=('Courier','25','bold'))
    b3.place(x=100,y=350)
    b3.bind("<Button-1>",py2)
    b4=Button(f2,text='BACK',font=('times','15','bold'))
    b4.place(x=10,y=10)
    b4.bind("<Button-1>",studies)
    b5=Button(f2,text='EXIT',font=('times','15','bold'))
    b5.place(x=1450,y=10)
    b5.bind("<Button-1>",exit)

def maths(self):
    f.destroy()
    f2=Frame(root,bg='black',width=2000,height=2000)
    f2.place(x=0,y=0)
    l0=Label(f2,image=p1)
    l0.place(x=700,y=150)
    l1=Label(f2,text="MATHEMATICS",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=650,y=10)
    b1=Button(f2,text="BY R. D. SHARMA",font=('Courier','25','bold'))
    b1.place(x=100,y=150)
    b1.bind("<Button-1>",rdsharma)
    b2=Button(f2,text="BY RAGHUBIR AGARWAL",font=('Courier','25','bold'))
    b2.place(x=100,y=250)
    b2.bind("<Button-1>",raghu)
    b3=Button(f2,text="NCERT",font=('Courier','25','bold'))
    b3.place(x=100,y=350)
    b3.bind("<Button-1>",ncert)
    b4=Button(f2,text='BACK',font=('times','15','bold'))
    b4.place(x=10,y=10)
    b4.bind("<Button-1>",studies)
    b5=Button(f2,text='EXIT',font=('times','15','bold'))
    b5.place(x=1450,y=10)
    b5.bind("<Button-1>",exit)

def bee(self):
    f.destroy()
    f2=Frame(root,bg='black',width=2000,height=2000)
    f2.place(x=0,y=0)
    l0=Label(f2,image=p1)
    l0.place(x=700,y=150)
    l1=Label(f2,text="BASIC ELECTRICAL ENGINEERING",bg='black',fg='white',font=('times','30','bold'))
    l1.place(x=450,y=10)
    b1=Button(f2,text="BY B. R. PATIL",font=('Courier','25','bold'))
    b1.place(x=100,y=150)
    b1.bind("<Button-1>",brpatil)
    b2=Button(f2,text="BY V. K. MEHTA",font=('Courier','25','bold'))
    b2.place(x=100,y=250)
    b2.bind("<Button-1>",vkmehta)
    b3=Button(f2,text="BY C. L. WADHWA",font=('Courier','25','bold'))
    b3.place(x=100,y=350)
    b3.bind("<Button-1>",clwadhwa)
    b4=Button(f2,text='BACK',font=('times','15','bold'))
    b4.place(x=10,y=10)
    b4.bind("<Button-1>",studies)
    b5=Button(f2,text='EXIT',font=('times','15','bold'))
    b5.place(x=1450,y=10)
    b5.bind("<Button-1>",exit)

def letusc(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p6)
    l0.place(x=30,y=400)
    l1=Label(f1,text="C LANGUAGE",bg ='black',fg='yellow',font=('times','40','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: LET US C",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR:YASHAVANT P. KATNEKAR",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 101",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 20 NOV 2002",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:165",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p7)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",clang)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def cprog1(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p59)
    l0.place(x=30,y=500)
    l1=Label(f1,text="C LANGUAGE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: PROGRAMMING IN C",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: REEMA THAREJA",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 102",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="DATE OF PUBLISH: 1 NOVEMBER 2014",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4.5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE:165",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p60)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",clang)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)

def cprog2(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p61)
    l0.place(x=30,y=500)
    l1=Label(f1,text=" C LANGUAGE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: C PROGRAMMING LANGUAGE",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: DARREL L. GRAHAM",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 103",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="DATE OF PUBLISH: 6 MARCH 2016",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 13",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 205",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p62)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",clang)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)

def reemads(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p8)
    l0.place(x=30,y=400)
    l1=Label(f1,text="DATA STRUCTURE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: DATA STRUCTURES USING C",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: REEMA THAREJA",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 104",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 11 JUNE 2014",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:150",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p9)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",ds)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def seymour(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p63)
    l0.place(x=30,y=500)
    l1=Label(f1,text="DATA STRUCTURES",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: DATA STRUCTURES",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: SEYMOUR LIPSHUTZ",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 105",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="YEAR OF PUBLISH: 2014",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 13",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 250",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p64)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",ds)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)

def bala(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p65)
    l0.place(x=30,y=500)
    l1=Label(f1,text="DATA STRUCTURES",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: DATA STRUCTURES USING C",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: E BALAGURUSAMY",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 106",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="YEAR OF PUBLISH: 2013",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 13",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4.7/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 250",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p66)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",ds)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)


def corepy(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p10)
    l0.place(x=30,y=400)
    l1=Label(f1,text="PYTHON LANGUAGE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: CORE PYTHON PROGRAMMING",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: R. NAGESHWARA RAO",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 107",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 1 JAN 2016",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.8/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:200",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p11)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",pyth)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def py1(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p67)
    l0.place(x=30,y=500)
    l1=Label(f1,text="PYTHON LANGUAGE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: PYTHON FOR BEGINNERS",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: TIMOTHY C. NEEDHAM",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 108",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="DATE OF PUBLISH: 10 SEPTEMBER 2017",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 8",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 3.8/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 165",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p68)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",pyth)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)

def py2(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p69)
    l0.place(x=30,y=500)
    l1=Label(f1,text="PYTHON LANGUAGE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: PYHTON PROGRAMMING",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: RAMSEY HAMILTON",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 109",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="DATE OF PUBLISH: 14 JUNE 2016",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 15",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4.3/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 190",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p70)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",pyth)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)


def rdsharma(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p12)
    l0.place(x=30,y=400)
    l1=Label(f1,text="MATHEMATICS",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: MATHEMATICS CLASS 12",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: R. D. SHARMA",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 110",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2018",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 3.9/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:160",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l8=Label(f1,image=p13)
    l8.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",maths)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def ncert(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p71)
    l0.place(x=30,y=500)
    l1=Label(f1,text="MATHEMATICS",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: NCERT",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="PUBLISHER: NATIONAL COUNCIL OF EDUCATION RESEARCH AND TRAINING",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 111",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="YEAR OF PUBLISH: 2012",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 9",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4.5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 260",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p72)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",maths)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)


def raghu(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p73)
    l0.place(x=30,y=500)
    l1=Label(f1,text="MATHEMATICS",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: TEXTBOOK FOR MATHEMATICS",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=100)
    l3=Label(f1,text="AUTHOR: RAGHUBIR AGARWAL",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 112",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="YEAR OF PUBLISH: 2015",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 20",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 3.8/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 150",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p74)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",maths)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)
  
def brpatil(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p14)
    l0.place(x=30,y=400)
    l1=Label(f1,text="BASIC ELECTRICAL ENGINEERING",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=600,y=20)
    l2=Label(f1,text="TITLE: BASIC ELECTRICAL ENGINEERING",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: B. R. PATIL",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 113",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 27 JULY 2017",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:150",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p15)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",bee)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)

def vkmehta(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p75)
    l0.place(x=30,y=500)
    l1=Label(f1,text="BASIC ELECTRICAL ENGINEERING",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l3=Label(f1,text="AUTHOR: V. K. MEHTA",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 114",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="DATE OF PUBLISH: 30 NOVEMBER 20",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 13",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 190",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p76)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",bee)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)

def clwadhwa(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p77)
    l0.place(x=30,y=500)
    l1=Label(f1,text="BASIC ELECTRICAL ENGINEERING",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l3=Label(f1,text="AUTHOR: C. L. WADHWA",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=150)
    l4=Label(f1,text="BOOK ID: 115",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=200)
    l5=Label(f1,text="DATE OF PUBLISH: 1 JANUARY 2007",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=250)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 19",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=300)
    l7=Label(f1,text="RATINGS: 4.7/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=350)
    l8=Label(f1,text="PRICE: 250",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=400)
    l9=Label(f1,image=p78)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",bee)
    b2=Button(f1,text='EXIT',font=('times','15','bold'))
    b2.place(x=1450,y=10)
    b2.bind("<Button-1>",exit)

def harry(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p16)
    l0.place(x=30,y=400)
    l1=Label(f1,text="HARRY POTTER",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: HARRY POTTER SERIES",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: J. K. ROWLING",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 201",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 1997",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:170",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p17)
    l9.place(x=900,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",fiction)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def twilight(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p18)
    l0.place(x=30,y=400)
    l1=Label(f1,text="TWILIGHT",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: TWILIGHT SERIES",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: STEPHENIE MEYER",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 202",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2005",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.7/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:230",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p19)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",fiction)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def lifeofpi(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p20)
    l0.place(x=30,y=400)
    l1=Label(f1,text="LIFE OF PI",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: LIFE OF PI",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: YANN MARTEL",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 203",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2001",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 3.9/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:199",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p21)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",fiction)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def divergent(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p22)
    l0.place(x=30,y=400)
    l1=Label(f1,text="DIVERGENT",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: DIVERGENT SERIES",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: VERONICA ROTH",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 204",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2011",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:299",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p23)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",fiction)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def got(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p24)
    l0.place(x=30,y=400)
    l1=Label(f1,text="GAME OF THRONES",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: GAME OF THRONES SERIES",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: GEORGE R. R. MARTIN",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 205",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 1996",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:399",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p25)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",fiction)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)
    
def steve(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p26)
    l0.place(x=30,y=400)
    l1=Label(f1,text="STEVE JOBS",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=600,y=20)
    l2=Label(f1,text="TITLE: MAN WHO THOUGHT DIFFERENT",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: KAREN BLUMENTHAL",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 401",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 14 FEB 2012",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.6/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:300",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p27)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",biography)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def bill(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p28)
    l0.place(x=30,y=400)
    l1=Label(f1,text="BILL GATES",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: A BIOGRAPHY",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: ROBERT SCHALLER",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 402",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2014",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:130",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p29)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",biography)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def apj(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p30)
    l0.place(x=30,y=400)
    l1=Label(f1,text="APJ ABDUL KALAM",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: A LIFE",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: ARUN TIWARI",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 403",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2015",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.7/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:170",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p31)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",biography)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def malala(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p32)
    l0.place(x=30,y=400)
    l1=Label(f1,text="MALALA",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: I AM MALALA",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: PATRICIA McGORMICK",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 404",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2 OCT 2015",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.6/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:145",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p33)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",biography)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def karan(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p34)
    l0.place(x=30,y=400)
    l1=Label(f1,text="KARAN JOHAR",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: AN UNSUITABLE BOY",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: POONAM SAXENA",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 405",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 16 FEB 2018",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 3.9/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:189",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p35)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",biography)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def tintin(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p36)
    l0.place(x=30,y=400)
    l1=Label(f1,text="TINTIN SERIES",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: TINTIN",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: HERGE",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 401",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="YEAR OF PUBLISH: 1946",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:179",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p37)
    l9.place(x=950,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",cartoons)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def snowwhite(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p38)
    l0.place(x=30,y=400)
    l1=Label(f1,text="SNOW WHITE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=600,y=20)
    l2=Label(f1,text="TITLE: SNOW WHITE AND SEVEN DWARFS",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="PUBLICATION: DREAMLAND PUBLICATION ",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 403",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="YEAR OF PUBLISH: 1990",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.6/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:199",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p39)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",cartoons)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def stories(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p40)
    l0.place(x=30,y=400)
    l1=Label(f1,text="GREAT STORIES FOR CHILDREN",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: GREAT STORIES FOR CHILDREN",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHOR: RUSKIN BOND",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 402",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2000",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.5/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:200",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p41)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",cartoons)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)



def junglebook(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p42)
    l0.place(x=30,y=400)
    l1=Label(f1,text="THE JUNGLE BOOK",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: THE JUNGLLE BOOK",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER: RUDYARD KIPLING",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 404",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="YEAR OF PUBLISH: 1894",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.7/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:169",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p43)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",cartoons)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def gulliver(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p44)
    l0.place(x=30,y=400)
    l1=Label(f1,text="GULLIVER TRAVELS",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE: GULLIVER'S TRAVELS",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER: JONATHAN SWIFT",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID: 405",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 28 OCT 1726",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE: 10",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS: 4.0/5",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:399",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p45)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",cartoons)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def diet(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p46)
    l0.place(x=30,y=500)
    l1=Label(f1,text="FLAT BELLY DIET",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE:FLAT BELLY DIET",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER:LIZ VACCARIELLO",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID:501 ",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH:24 APRIL,2012",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE:25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.0",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:279",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p47)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",health)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def eatcomplete(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p48)
    l0.place(x=30,y=400)
    l1=Label(f1,text="EAT COMPLETE",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE:EAT COMPLETE",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER:DREW RANSEY",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID:502 ",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH:17 MAY,2016",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE:25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.1",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:179",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p49)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",health)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def arthealth(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p50)
    l0.place(x=30,y=400)
    l1=Label(f1,text="THE ART OF HEALTH",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE:THE ART OF HEALTH",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER:AARTI PATEL",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID:503",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH:2 SEPTEMBER,2018",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE:25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.3",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:199",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p51)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",health)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def metabolism(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p52)
    l0.place(x=30,y=400)
    l1=Label(f1,text="MASTER YOUR METABOLISM",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE:MASTER YOUR METABOLISM",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER:Jillian Michaels",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID:504",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 27 April, 2010",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE:25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.4",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:289",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p53)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",health)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)


def pillars(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p54)
    l0.place(x=30,y=400)
    l1=Label(f1,text="SEVEN PILLARS OF HEALTH",bg ='black',fg='yellow',font=('times','30','italic underline'))
    l1.place(x=550,y=20)
    l2=Label(f1,text="TITLE:SEVEN PILLARS OF HEALTH",bg ='black',fg='yellow',font=('times','20','italic'))
    l2.place(x=50,y=50)
    l3=Label(f1,text="AUTHER:DON CONBERT",bg ='black',fg='yellow',font=('times','20','italic'))
    l3.place(x=50,y=100)
    l4=Label(f1,text="BOOK ID:504",bg ='black',fg='yellow',font=('times','20','italic'))
    l4.place(x=50,y=150)
    l5=Label(f1,text="DATE OF PUBLISH: 2008",bg ='black',fg='yellow',font=('times','20','italic'))
    l5.place(x=50,y=200)
    l6=Label(f1,text="NUMBER OF COPIES AVAILABLE:25",bg ='black',fg='yellow',font=('times','20','italic'))
    l6.place(x=50,y=250)
    l7=Label(f1,text="RATINGS:4.4",bg ='black',fg='yellow',font=('times','20','italic'))
    l7.place(x=50,y=300)
    l8=Label(f1,text="PRICE:189",bg ='black',fg='yellow',font=('times','20','italic'))
    l8.place(x=50,y=350)
    l9=Label(f1,image=p55)
    l9.place(x=1000,y=100)
    b1=Button(f1,text='BACK',font=('times','15','bold'))
    b1.place(x=10,y=10)
    b1.bind("<Button-1>",health)
    b7=Button(f1,text='EXIT',font=('times','15','bold'))
    b7.place(x=1450,y=10)
    b7.bind("<Button-1>",exit)



def exit(self):
    f.destroy()
    f1=Frame(root,bg='black',width=2000,height=2000)
    f1.place(x=0,y=0)
    l0=Label(f1,image=p57)
    l0.place(x=100,y=100)
    l1=Label(f1,text='THANK YOU FOR VISITING OUR STORE',bg ='black',fg='red',font=('times','30','italic underline'))
    l1.place(x=800,y=750)
    l2=Label(f1,image=p58)
    l2.place(x=1200,y=100)


f=Frame(root,bg='black',height=2000,width=2000)
f.propagate(0)
f.place(x=0,y=0)
l0=Label(f,image=p)
l0.place(x=200,y=100)
fnt=('Times','40','bold italic underline ')
l1=Label(f,text="KITAB KHANA",bg='black',fg='white',font=fnt)
l1.place(x=550,y=10)
l3=Label(f,text="USERNAME:",font=('times','30','bold'))
l3.place(x=350,y=200)
l4=Label(f,text="PASSWORD:",font=('times','30','bold'))
l4.place(x=350,y=300)
t1=Entry(f,width=35)
t1.place(x=800,y=215)
t2=Entry(f,width=35,show="*")
t2.place(x=800,y=315)
b1=Button(f,text="LOGIN",font=('times','30','bold'))
b1.place(x=400,y=500)
b1.bind("<Button-1>",login)
b2=Button(f,text="REGISTER",font=('times','30','bold'))
b2.place(x=800,y=500)
b2.bind("<Button-1>",register)

root.mainloop()

